name: Deploy Svelte Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10.9.0'

      - name: Install dependencies
        run: |
          cd ./banana_frontend
          npm install

      #- name: Build the Svelte app
      #  run: |
      #    cd ./banana_frontend
      #    npm run build

      - name: Build and push Docker image
        run: |
          docker build -t jansuklje/banana-frontend:latest -f ./banana_frontend/Dockerfile ./banana_frontend
          docker push jansuklje/banana-frontend:latest

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run deploy script on local server
        run: |
          ssh -tt -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} \
            'sudo bash /home/user/dockers/deploy_svelte.sh'
